[project]
name = "fastqstats"
version = "0.1.0"
description = "A FASTQ Quality control and summary tool"
authors = [
	{name = "Martin TÃ¶rn"}
]
dependencies = [
	"numpy",
	"pandas"
]

[project.scripts]
fastqstats = "fastqstats.cli:main"